export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';
export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_MEAL_BY_ID = 'FETCH_MEAL_BY_ID';
