export const LOADING_STATUS = 'LOADING_STATUS';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';
export const FETCH_MEALS = 'FETCH_MEALS';
export const FETCH_MEAL_BY_ID = 'FETCH_MEAL_BY_ID';
export const SEARCH_MEAL = 'SEARCH_MEAL';
export const FETCH_MEAL_BY_SEARCH = 'FETCH_MEAL_BY_SEARCH';
